Repository saphal-sip-org/attendance-tracker, pull requests merged in 2024-05, with the labels that each got.

#3 updated readme
  README.md
Labels: documentation

#6 setup FrontEnd folder structure
  client/postcss.config.js
  client/src/App.css
  client/src/App.jsx
  client/src/assets/react.svg
  client/tailwind.config.js
Labels: enhancement

#8 Pages created
  client/package.json
  client/src/App.jsx
  client/src/index.css
  client/src/routes/pages/Home.jsx
  client/src/routes/pages/Login.jsx
  client/yarn.lock
Labels: enhancement

#12 components added
  client/src/components/Button.jsx
  client/src/components/Input.jsx
  client/src/routes/pages/Login.jsx
  client/tailwind.config.js
Labels: enhancement, Feature request

#15 commoncreated
  client/src/components/common/Button.jsx
  client/src/components/common/Input.jsx
  client/src/routes/pages/Login.jsx
Labels: enhancement

#11 schema added
  server/index.js
  server/models/schemas/attendance.js
  server/models/schemas/course.js
  server/models/schemas/schemas.js
  server/models/schemas/student.js
  server/models/schemas/teacher.js
  server/modules/connection.js
  server/package.json
  server/routers/routers.js
  server/routers/teacher.js
  server/yarn.lock
Labels: enhancement

#17 Updated: package.json
  server/package.json
Labels: enhancement

#18 loginUicreated
  client/src/components/common/Button.jsx
  client/src/components/common/Input.jsx
  client/src/images/loginp.svg
  client/src/routes/pages/Login.jsx
Labels: enhancement, Feature request

#20 Feature/loginchanged
  client/src/components/common/Input.jsx
  client/src/routes/pages/Login.jsx
  client/tailwind.config.js
Labels: enhancement, Feature request

#21 issues fix: database & schema issues
  server/controllers/teacherLogin.js
  server/controllers/teacherLogout.js
  server/controllers/teacherRegister.js
  server/index.js
  server/models/schemas/schemas.js
  server/modules/connection.js
  server/package.json
  server/routers/teacher.js
  server/routers/teacherRouter.js
Labels: bug

#24 added: sidebar
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/navbar/Sidebar.jsx
  client/src/routes/pages/Home.jsx
  client/yarn.lock
Labels: enhancement, Feature request

#26 added: router to add new student
  server/controllers/teacherControllers/teacherAddNewStudent.js
  server/controllers/teacherControllers/teacherRegister.js
  server/routers/teacherRouter.js
Labels: enhancement, Feature request

#29 Added: reuseable menuItem & navelink
  client/.eslintrc.cjs
  client/package-lock.json
  client/src/components/common/menuItem.jsx
  client/src/components/navbar/Sidebar.jsx
  client/yarn.lock
Labels: enhancement, Feature request

#30 refactor: login ui
  client/src/components/common/Button.jsx
  client/src/routes/pages/Login.jsx
Labels: enhancement

#35 refactor: navbar & input
  client/src/components/common/Button.jsx
  client/src/components/common/Input.jsx
  client/src/components/navbar/Dashboard.jsx
  client/src/components/navbar/Sidebar.jsx
  client/src/routes/pages/Login.jsx
  client/src/routes/pages/Register.jsx
  client/tailwind.config.js
Labels: enhancement

#36 Add permission schema
  server/models/schemas/permission.js
  server/models/schemas/schemas.js
Labels: enhancement

#38 Added & updated: register validator
  server/controllers/register.js
  server/helpers/validator.js
  server/package.json
  server/routers/router.js
  server/yarn.lock
Labels: enhancement, Feature request

#39 User register validator
  server/controllers/register.js
Labels: enhancement

#40 add name in register
  client/src/routes/pages/Register.jsx
Labels: enhancement, Feature request

#41 add name in register
  client/src/routes/pages/Register.jsx
Labels: enhancement, Feature request

#34 Development branch
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/UserDropDown.jsx
  client/src/components/common/Button.jsx
  client/src/components/common/Input.jsx
  client/src/components/common/menuItem.jsx
  client/src/components/navbar/Dashboard.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/components/navbar/Sidebar.jsx
  client/src/images/login.svg
  client/src/images/loginp.svg
  client/src/routes/pages/Home.jsx
  client/src/routes/pages/Login.jsx
  client/src/routes/pages/Register.jsx
  client/tailwind.config.js
  client/yarn.lock
  server/controllers/login.js
  server/controllers/logout.js
  server/controllers/newStudent.js
  server/controllers/register.js
  server/helpers/validator.js
  server/index.js
  server/models/schemas/attendance.js
  server/models/schemas/course.js
  server/models/schemas/permission.js
  server/models/schemas/schemas.js
  server/models/schemas/student.js
  server/models/schemas/user.js
  server/modules/connection.js
  server/package.json
  server/routers/router.js
  server/yarn.lock
Labels: enhancement, Feature request

#44 Added & updated: validator & login router
  server/controllers/login.js
  server/controllers/newStudent.js
  server/controllers/register.js
  server/helpers/validator.js
  server/routers/router.js
Labels: enhancement, Feature request

#45 refactor: role
  server/controllers/login.js
Labels: bug

#46 refactor: userPermission
  server/models/schemas/user.js
  server/models/schemas/userPermission.js
Labels: enhancement

#47 Added: permissionModel for user role
  server/models/schemas/permissionModel.js
Labels: enhancement, Feature request

#48 added: admin permission controller
  server/controllers/admin/permissionController.js
  server/controllers/auth/login.js
  server/controllers/auth/register.js
  server/helpers/adminValidator.js
  server/helpers/authValidator.js
  server/index.js
  server/routers/adminRouter.js
  server/routers/authRouter.js
Labels: enhancement, Feature request

#49 added : auth & getProfile , resolved : issues & bug, refactor: login controller
  server/controllers/auth/getProfile.js
  server/controllers/auth/login.js
  server/controllers/auth/register.js
  server/index.js
  server/middlewares/authMiddleware.js
  server/routers/authRouter.js
Labels: bug, enhancement, Feature request

#50 added : read, Update, Delete Admin permission
  server/controllers/admin/addPermissionController.js
  server/controllers/admin/deletePermissionController.js
  server/controllers/admin/getPermissionController.js
  server/controllers/admin/updatePermissionController.js
  server/helpers/adminValidator.js
  server/routers/adminRouter.js
Labels: enhancement, Feature request

#51 added : only admin access middleware
  server/middlewares/adminMiddleware.js
  server/middlewares/authMiddleware.js
  server/routers/adminRouter.js
  server/yarn.lock
Labels: enhancement, Feature request

#54 Added: outlet(raw of attendance controller)
  server/controllers/common/attendance/addAttendanceController.js
  server/controllers/common/attendance/deleteAttendanceController.js
  server/controllers/common/attendance/getAttendanceController.js
  server/controllers/common/attendance/updateAttendanceController.js
  server/controllers/common/attendanceController.js
  server/controllers/common/student/addStudentController.js
  server/controllers/common/student/deleteStudentController.js
  server/controllers/common/student/getEachStudentController.js
  server/controllers/common/student/getStudentController.js
  server/controllers/common/student/updateStudentController.js
  server/controllers/common/studentController.js
  server/helpers/commonValidator.js
  server/index.js
  server/models/schemas/attendance.js
  server/routers/attendanceRouter.js
  server/routers/courseRouter.js
  server/routers/studentRouter.js
Labels: enhancement, Feature request

#55 refactor : student router & schema
  server/helpers/commonValidator.js
  server/models/schemas/student.js
  server/routers/studentRouter.js
Labels: enhancement

#57 refactor: student controller
  server/controllers/common/course/addCourseController.js
  server/controllers/common/course/deleteCourseController.js
  server/controllers/common/course/getCourseController.js
  server/controllers/common/course/updateCourseController.js
  server/controllers/common/student/addStudentController.js
  server/controllers/common/student/deleteStudentController.js
  server/controllers/common/student/getEachStudentController.js
  server/controllers/common/student/getStudentController.js
  server/controllers/common/student/updateStudentController.js
  server/helpers/commonValidator.js
  server/routers/studentRouter.js
Labels: enhancement

#58 update & refactor : validator, model, router & controller
  server/controllers/common/attendance/addAttendanceController.js
  server/controllers/common/attendance/deleteAttendanceController.js
  server/controllers/common/attendance/getAttendanceController.js
  server/controllers/common/attendance/setHolidayController.js
  server/controllers/common/attendance/updateAttendanceController.js
  server/controllers/common/student/addStudentController.js
  server/controllers/common/student/deleteStudentController.js
  server/controllers/common/student/getEachStudentController.js
  server/controllers/common/student/getStudentController.js
  server/controllers/common/student/updateStudentController.js
  server/helpers/commonValidator.js
  server/index.js
  server/models/schemas/attendance.js
  server/models/schemas/student.js
  server/routers/attendanceRouter.js
Labels: enhancement

#59 added: roles
  server/controllers/admin/addPermissionController.js
  server/controllers/admin/getRolesController.js
  server/controllers/admin/storeRoleController.js
  server/helpers/adminValidator.js
  server/middlewares/adminUserMiddleware.js
  server/models/schemas/roleModel.js
  server/routers/adminRouter.js
Labels: enhancement

#60 added: teacher router & controller
  server/controllers/common/teacher/addTeacherController.js
  server/controllers/common/teacher/deleteTeacherController.js
  server/controllers/common/teacher/getEachTeacherController.js
  server/controllers/common/teacher/getTeacherController.js
  server/controllers/common/teacher/updateTeacherController.js
  server/controllers/common/teacherController.js
  server/helpers/commonValidator.js
  server/index.js
  server/models/schemas/teacher.js
  server/routers/teacherRouter.js
Labels: enhancement, Feature request

#61 added : query for permissions
  server/controllers/auth/login.js
  server/controllers/auth/register.js
Labels: enhancement

#62 refactor: register
  server/controllers/auth/getProfile.js
  server/controllers/auth/register.js
Labels: enhancement

#63 refactor : some issues
  server/controllers/auth/getProfile.js
  server/controllers/auth/register.js
  server/controllers/common/teacher/getTeacherController.js
  server/controllers/common/user/createUserController.js
  server/controllers/common/user/getUser.js
  server/package.json
  server/yarn.lock
Labels: enhancement

#64 added: create user controller
  server/controllers/common/user/createUserController.js
  server/helpers/mailer.js
  server/package.json
  server/yarn.lock
Labels: enhancement
